[tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
# keep it friendly to start with. Black handles line length, ignore E501 to avoid duplicate noise.
select = ["E", "F", "I", "B", "UP"] # pycodestyle, pyflakes, import sort checks, flake-bugbear, pyupgrade
ignore = ["E501"]

[tool.black]
line-length = 100
target-version = ["py312"]

[tool.isort]
profile = "black"
line_length = 100
